version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-latest-1
      - test-latest
jobs:
  test-latest-1:
    docker:
      - image: "circleci/golang:1.12"
    steps: &ref_0
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: go test -v ./...
      - run: go install ./...
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  test-latest:
    docker:
      - image: "circleci/golang:1.13"
    steps: *ref_0
